### ISSUE TITLE
where is your dataset ?

### ISSUE THREAD

**Issue by xiaoqun-growing** [DCMMC/EBSNN#1]
I just read your paper, it is a wonderful job for me to continue learning. However, the dataset you have pointed out is invalid. Please tell us  the valid link of dataset. Thanks for your consideration!

**Comment by DCMMC** [comment]
Hi xiaoqun, thank you for your interest in our work. You can find the URL of our dataset in the footnote of page 6 of our paper, which is https://drive.google.com/drive/folders/1-I3a3lM6v_ANU6uu_AUmpNYt7rGu3kzt.

**Comment by xiaoqun-growing** [comment]
OK! It's my fault, I get it! Thank you!
